### PR TITLE
Da ticket4

### PR DESCRIPTION
**Pull request by DarylAdkins**
## Proposed changes
This is the build of the Order Controller. This Order controller allows a developer to GET all entities in the Order table in Database, GET a single entity in the Order table, POST an entity into the Order table, PUT an existing entity in the Order table, and then DELETE a single entity in the Order table. This controller in conjunction with the Order model satisfies the requirements for ticket #4. 

## Related Issues
Provides order model that is needed for the other developers on the team

## Steps To Test
Build your Bangazon Database by running the following 2 sets of SQL scripts.

(Build Database)
DELETE FROM OrderProduct;
DELETE FROM ComputerEmployee;
DELETE FROM EmployeeTraining;
DELETE FROM Employee;
DELETE FROM TrainingProgram;
DELETE FROM Computer;
DELETE FROM Department;
DELETE FROM [Order];
DELETE FROM PaymentType;
DELETE FROM Product;
DELETE FROM ProductType;
DELETE FROM Customer;

ALTER TABLE Employee DROP CONSTRAINT [FK_EmployeeDepartment];
ALTER TABLE ComputerEmployee DROP CONSTRAINT [FK_ComputerEmployee_Employee];
ALTER TABLE ComputerEmployee DROP CONSTRAINT [FK_ComputerEmployee_Computer];
ALTER TABLE EmployeeTraining DROP CONSTRAINT [FK_EmployeeTraining_Employee];
ALTER TABLE EmployeeTraining DROP CONSTRAINT [FK_EmployeeTraining_Training];
ALTER TABLE Product DROP CONSTRAINT [FK_Product_ProductType];
ALTER TABLE Product DROP CONSTRAINT [FK_Product_Customer];
ALTER TABLE PaymentType DROP CONSTRAINT [FK_PaymentType_Customer];
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_Customer];
ALTER TABLE [Order] DROP CONSTRAINT [FK_Order_Payment];
ALTER TABLE OrderProduct DROP CONSTRAINT [FK_OrderProduct_Product];
ALTER TABLE OrderProduct DROP CONSTRAINT [FK_OrderProduct_Order];

DROP TABLE IF EXISTS OrderProduct;
DROP TABLE IF EXISTS ComputerEmployee;
DROP TABLE IF EXISTS EmployeeTraining;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS TrainingProgram;
DROP TABLE IF EXISTS Computer;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS [Order];
DROP TABLE IF EXISTS PaymentType;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS ProductType;
DROP TABLE IF EXISTS Customer;

CREATE TABLE Department (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(55) NOT NULL,
	Budget 	INTEGER NOT NULL
);

CREATE TABLE Employee (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FirstName VARCHAR(55) NOT NULL,
	LastName VARCHAR(55) NOT NULL,
	DepartmentId INTEGER NOT NULL,
	IsSuperVisor BIT NOT NULL DEFAULT(0),
    CONSTRAINT FK_EmployeeDepartment FOREIGN KEY(DepartmentId) REFERENCES Department(Id)
);

CREATE TABLE Computer (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	PurchaseDate DATETIME NOT NULL,
	DecomissionDate DATETIME,
	Make VARCHAR(55) NOT NULL,
	Manufacturer VARCHAR(55) NOT NULL
);

CREATE TABLE ComputerEmployee (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	EmployeeId INTEGER NOT NULL,
	ComputerId INTEGER NOT NULL,
	AssignDate DATETIME NOT NULL,
	UnassignDate DATETIME,
    CONSTRAINT FK_ComputerEmployee_Employee FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
    CONSTRAINT FK_ComputerEmployee_Computer FOREIGN KEY(ComputerId) REFERENCES Computer(Id)
);

CREATE TABLE TrainingProgram (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(255) NOT NULL,
	StartDate DATETIME NOT NULL,
	EndDate DATETIME NOT NULL,
	MaxAttendees INTEGER NOT NULL
);

CREATE TABLE EmployeeTraining (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	EmployeeId INTEGER NOT NULL,
	TrainingProgramId INTEGER NOT NULL,
    CONSTRAINT FK_EmployeeTraining_Employee FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
    CONSTRAINT FK_EmployeeTraining_Training FOREIGN KEY(TrainingProgramId) REFERENCES TrainingProgram(Id)
);

CREATE TABLE ProductType (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(55) NOT NULL
);

CREATE TABLE Customer (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	FirstName VARCHAR(55) NOT NULL,
	LastName VARCHAR(55) NOT NULL
);

CREATE TABLE Product (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	ProductTypeId INTEGER NOT NULL,
	CustomerId INTEGER NOT NULL,
	Price MONEY NOT NULL,
	Title VARCHAR(255) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	Quantity INTEGER NOT NULL,
    CONSTRAINT FK_Product_ProductType FOREIGN KEY(ProductTypeId) REFERENCES ProductType(Id),
    CONSTRAINT FK_Product_Customer FOREIGN KEY(CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE PaymentType (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	AcctNumber INTEGER NOT NULL,
	[Name] VARCHAR(55) NOT NULL,
	CustomerId INTEGER NOT NULL,
    CONSTRAINT FK_PaymentType_Customer FOREIGN KEY(CustomerId) REFERENCES Customer(Id)
);

CREATE TABLE [Order] (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	CustomerId INTEGER NOT NULL,
	PaymentTypeId INTEGER,
    CONSTRAINT FK_Order_Customer FOREIGN KEY(CustomerId) REFERENCES Customer(Id),
    CONSTRAINT FK_Order_Payment FOREIGN KEY(PaymentTypeId) REFERENCES PaymentType(Id)
);

CREATE TABLE OrderProduct (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	OrderId INTEGER NOT NULL,
	ProductId INTEGER NOT NULL,
    CONSTRAINT FK_OrderProduct_Product FOREIGN KEY(ProductId) REFERENCES Product(Id),
    CONSTRAINT FK_OrderProduct_Order FOREIGN KEY(OrderId) REFERENCES [Order](Id)
);

(Populate the datatables)
DELETE FROM Customer;
DELETE FROM ProductType;
DELETE FROM Department;
DELETE FROM TrainingProgram;
DELETE FROM Computer;
DELETE FROM Employee;
DELETE FROM Product;
DELETE FROM PaymentType;
DELETE FROM [Order];
DELETE FROM OrderProduct;
DELETE FROM ComputerEmployee;
DELETE FROM EmployeeTraining;
INSERT INTO Computer (PurchaseDate, Make, Manufacturer) VALUES ('06/26/1982','Latitude', 'Dell')
INSERT INTO Computer (PurchaseDate, Make, Manufacturer) VALUES ('04/16/1999','Inspiron', 'Dell')
INSERT INTO Computer (PurchaseDate, Make, Manufacturer) VALUES ('03/13/2010','Latitude', 'Dell')
INSERT INTO Customer (FirstName, LastName) VALUES ('Fred','Smith')
INSERT INTO Customer (FirstName, LastName) VALUES ('Sally','Jones')
INSERT INTO Customer (FirstName, LastName) VALUES ('Bob','Robertson')
INSERT INTO Department (Name, Budget) VALUES ('Sales', 501245)
INSERT INTO Department (Name, Budget) VALUES ('Marketing', 99801)
INSERT INTO Department (Name, Budget) VALUES ('Human Resources', 50879)
INSERT INTO ProductType (Name) VALUES ('Kitchen Wares')
INSERT INTO ProductType (Name) VALUES ('Toys')
INSERT INTO ProductType (Name) VALUES ('Shoes')
INSERT INTO TrainingProgram (Name, StartDate, EndDate, MaxAttendees) VALUES ('New Hire Orientation', '02/13/2011', '03/02/2019', 50)
INSERT INTO TrainingProgram (Name, StartDate, EndDate, MaxAttendees) VALUES ('New Hire Orientation', '05/13/2018', '01/22/2019', 50)
INSERT INTO TrainingProgram (Name, StartDate, EndDate, MaxAttendees) VALUES ('New Hire Orientation', '08/13/2001', '06/02/2015', 50)
INSERT INTO Employee (FirstName, LastName, DepartmentId, IsSupervisor) VALUES ('Fred','Smith', 2, 0)
INSERT INTO Employee (FirstName, LastName, DepartmentId, IsSupervisor) VALUES ('John','Johnson', 2, 0)
INSERT INTO Employee (FirstName, LastName, DepartmentId, IsSupervisor) VALUES ('Larry','Larryson', 3, 1)
INSERT INTO EmployeeTraining (EmployeeId, TrainingProgramId) VALUES (2, 1)
INSERT INTO EmployeeTraining (EmployeeId, TrainingProgramId) VALUES (1, 1)
INSERT INTO EmployeeTraining (EmployeeId, TrainingProgramId) VALUES (2, 2)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (9001,'Steve Stevenson', 1)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (9002, 'Mary Maryson', 1)
INSERT INTO PaymentType (AcctNumber, Name, CustomerId) VALUES (9003, 'Mike Michaelson', 2)
INSERT INTO Product (ProductTypeId, CustomerId, Price, Title, Description, Quantity) VALUES (2, 2, 9.99, 'Nerf Gun', 'Big gun shoots soft bullets', 1)
INSERT INTO Product (ProductTypeId, CustomerId, Price, Title, Description, Quantity) VALUES (1, 2, 3.99, 'Dawn Dish Soap', 'Takes grease out of the way', 1)
INSERT INTO Product (ProductTypeId, CustomerId, Price, Title, Description, Quantity) VALUES (3, 1, 6.99, 'Sandals', 'Beach Shoes', 1)
INSERT INTO [Order] (CustomerId, PaymentTypeId) VALUES (2, 1)
INSERT INTO [Order] (CustomerId, PaymentTypeId) VALUES (1,1)
INSERT INTO [Order] (CustomerId, PaymentTypeId) VALUES (1, 1)
INSERT INTO OrderProduct (OrderId, ProductId) VALUES (2, 1)
INSERT INTO OrderProduct (OrderId, ProductId) VALUES (2, 2)
INSERT INTO OrderProduct (OrderId, ProductId) VALUES (1, 1)

After pulling the branch from github, run in visual studio 2019. Start program by selecting by hitting green play button. After chrome opens, note the local host number generated in the address bar, you will need this number when using the Postman app. Once the program is running, open up the Postman desktop app and run the following commands:

select GET then paste localhost # from the chrome url address bar and then type "order" into the field and click send. The result should be an array of all the orders in the database.

select GET then paste localhost # from the chrome url address bar and then type "order?completed=true" into the field and click send. The result should be an array of all the orders in the database that are completed. 

select GET then paste localhost # from the chrome url address bar and then type "order?completed=false" into the field and click send. The result should be an array of all the orders in the database that are completed. 

select GET then paste localhost # from the chrome url address bar and then type "order/1" and click send. The result should be only that object of the specified Order

select POST, then paste localhost # from the chrome url address bar and then type "order" into the field, then click Body underneath the field, then select raw, and then paste this snippet or make one similar
{
    "customerId": 2
    "paymentTypeId": 1
}
then click send. The result should be the new Order you made.

select PUT then paste localhost # from the chrome url address bar and then type "order/3", then click Body underneath the field, then select raw, and then paste this snippet or make one similar
{
    "id": 3,
    "customerId": 2
    "paymentTypeId": 2
}
You should get nothing back from this. When you run the GET query the order you specified in your PUT query should show the updated, edited information you gave it.

select DELETE then paste localhost # from the chrome url address bar and then type "order/2" (FK in the OrderProduct table) then click send. You should get nothing back from this. When you run the GET query the computer you specified in your DELETE query should no longer exist.

select DELETE then paste localhost # from the chrome url address bar and then type "order/3" (not a FK in the OrderProduct table) then click send. You should get nothing back from this. When you run the GET query the computer you specified in your DELETE query should no longer exist.

Run integration test scripts by selecting OrderControllerTest File located in the Bangazon API Folder and selecting Test Tab and thin run all tests. All tests should run successfully.

## What kind of change does this PR introduce?
Please check one of the following:
- [ ] Bug fix
- [X ] Documentation update
- [X ] New feature
- [ ] Other

### CODE REVIEW

**Comment by Jengwen** [comment]
Having trouble with PUT and POST, also unsure if the completed orders are coming back correctly.

**Comment by DarylAdkins** [comment]
I have updated the instructions on this PR to be accurate, hopefully.

**Comment by AllxnCook** [comment]
All tests passed.
Working on my machine.
Able to create, add, delete, and edit an order.
great job!

**Comment by Jengwen** [comment]
All the features are working great.

**Pull request merged**
